import { Project } from '../types';
// Force sync comment
export const mockProjects: Project[] = [
  {
    id: '1',
    name: '신규 브랜드 런칭 캠페인',
    status: 'ongoing',
    taskCell: 'UX셀',
    deadline: '2024-05-30',
    startDate: '2024-04-01',
    endDate: '2024-05-30',
    progress: 70,
    pm: '김철수',
    assignees: ['이영희', '박민수'],
    issues: ['예산 승인 대기 중'],
    tasks: ['SNS 광고 시안 제작', '인플루언서 섭외'],
    draftConfirmed: true,
    attachments: ['https://picsum.photos/seed/marketing/800/450'],
  },
  {
    id: '2',
    name: '웹사이트 리뉴얼 프로젝트',
    status: 'ongoing',
    taskCell: '영상셀',
    deadline: '2024-06-15',
    startDate: '2024-03-15',
    endDate: '2024-06-15',
    progress: 45,
    pm: '최지우',
    assignees: ['정다은', '강현우'],
    issues: ['API 연동 지연'],
    tasks: ['메인 페이지 퍼블리싱', '로그인 기능 구현'],
    draftConfirmed: false,
    attachments: [],
  },
  {
    id: '3',
    name: '하반기 전략 수립',
    status: 'upcoming',
    taskCell: '편집셀',
    deadline: '2024-07-01',
    startDate: '2024-06-01',
    endDate: '2024-07-01',
    progress: 0,
    pm: '한소희',
    assignees: ['김태리'],
    issues: [],
    tasks: ['시장 조사', '경쟁사 분석'],
    draftConfirmed: false,
    attachments: [],
  },
  {
    id: '4',
    name: '서버 유지보수',
    status: 'regular',
    taskCell: '공통',
    deadline: '2024-12-31',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    progress: 90,
    pm: '이정재',
    assignees: ['정우성'],
    issues: [],
    tasks: ['로그 모니터링', '보안 패치'],
    draftConfirmed: true,
    attachments: [],
  },
  {
    id: '5',
    name: '고객 센터 시스템 오류',
    status: 'issue',
    taskCell: 'UX셀',
    deadline: '2024-04-20',
    startDate: '2024-04-15',
    endDate: '2024-04-20',
    progress: 20,
    pm: '송강호',
    assignees: ['배두나'],
    issues: ['데이터 손실 위험'],
    tasks: ['DB 복구 작업', '고객 안내'],
    draftConfirmed: false,
    attachments: [],
  },
  {
    id: '6',
    name: '1분기 정기 보고서 완료',
    status: 'completed',
    taskCell: '편집셀',
    deadline: '2024-03-31',
    startDate: '2024-03-01',
    endDate: '2024-03-31',
    progress: 100,
    pm: '유재석',
    assignees: ['조세호'],
    issues: [],
    tasks: ['데이터 취합', '보고서 작성', '이사회 보고'],
    draftConfirmed: true,
    attachments: ['https://picsum.photos/seed/report/800/450'],
  },
];
